import type { Config } from "tailwindcss";
import defaultTheme from "tailwindcss/defaultTheme";

// we can add custom tailwind config here
// most of these settings are generated by shadcn/ui
const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      backgroundColor: {
        'green-400': 'rgb(74 222 128)', 
        'green-500': 'rgb(34 197 94)',
        'green-700': 'rgb(21 128 61)',
        'green-800': 'rgb(22 101 52)',
        'green-900': 'rgb(20 83 45)',
        'bg-green-100': '#dcfce7',
        'bg-green-200': '#bbf7d0',
        'bg-green-300': '#86efac',
        'bg-green-400': '#4ade80',
        'bg-green-500': '#22c55e',
        'bg-green-600': '#16a34a',
        'bg-green-700': '#15803d',
        'bg-green-800': '#166534',
        'bg-green-900': '#14532d',
      },
      colors: {
        // we can add custom colors here
        // this brand color is the iconic twitter blue
        // to use it, we can do `className="text-brand"` in our components
        // just like we do `className="text-red-500"` for tailwind's red color
        brand: "#1e9bf0",
        'bg-green-100': '#dcfce7',
        'bg-green-200': '#bbf7d0',
        'bg-green-300': '#86efac',
        'bg-green-400': '#4ade80',
        'bg-green-500': '#22c55e',
        'bg-green-600': '#16a34a',
        'bg-green-700': '#15803d',
        'bg-green-800': '#166534',
        'bg-green-900': '#14532d',
      },
      fontFamily: {
        // the `--noto-sans` variable is defined in `./src/app/layout.tsx`
        // now if we do `className="font-sans"` in our components, it will use Noto Sans
        sans: ["var(--noto-sans)", ...defaultTheme.fontFamily.sans],
      },
      // these keyframes and animations are from added by shadcn/ui
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
